### ISSUE TITLE
Run tests on pull-requests

### ISSUE THREAD

**Issue by haesleinhuepf** [haesleinhuepf/git-bob-playground#146]
I have a github workflow that is executed according to this config:

```
name: tests

on:
  push:
     branches:
       - master
       - main
  pull_request:
    branches:
      - master
      - main
```

How can I change it so that the tests are also executed in pull-requests to other branches than master and main?

git-bob answer
